package com.opencv.ama.core.model;

/** Where an answer came from. */
public enum AnswerSource {
    /** Matched from the knowledge base (question/answer pairs). */
    KNOWLEDGE,
    /** Generated by an AI provider (OpenAI, Anthropic, Gemini, Ollama, ...). */
    AI,
    /** Written by an admin/reviewer. */
    HUMAN
}
